import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/Shared/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import Navbar from '@/components/navbar/Navbar';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Eventesia',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AuthProvider>
            <div>
              <Navbar/>
              <div className=" ">
                {children}
              </div>
              <Toaster/>
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>{" "}
    </html>
  );
}
